from itertools import product
from typing import Any

from src.common.constants import (
    InstrumentGroup,
    PatternType,
    Pitch,
    Position,
    RuleValue,
    Stroke,
)
from src.common.notes import GenericNote, Note, NoteFactory, Tone
from src.notation2midi.rules.rule import Instrument
from src.notation2midi.rules.rule_cast_to_position import RuleCastToPosition
from src.settings.constants import NoteFields
from src.settings.settings import Settings
from tests.conftest import BaseUnitTestCase


class ValidNoteTester(BaseUnitTestCase):

    def load_settings(self, group: InstrumentGroup) -> dict:
        if group is InstrumentGroup.GONG_KEBYAR:
            composition = "test-gongkebyar"
        elif group is InstrumentGroup.SEMAR_PAGULINGAN:
            composition = "test-semarpagulingan"
        else:
            raise ValueError(f"invalid instrument group {group}")
        return Settings.get(notation_id=composition, part_id="full")

    # Combinations that will be tested (contains both valid and invalid combinations)
    TRY_COMBINATIONS: list[dict[str, Any]] = [
        {
            Note.Fields.POSITION: position,
            Note.Fields.PITCH: pitch,
            Note.Fields.OCTAVE: octave,
            Note.Fields.EFFECT: effect,
            Note.Fields.NOTE_VALUE: duration,
            Note.Fields.AUTOGENERATED: autogenerated,
        }
        for position in (Position.PEMADE_POLOS, Position.JEGOGAN, Position.REYONG_1)
        for pitch in [Pitch.DING, Pitch.DAING, Pitch.STRIKE, Pitch.DAG, Pitch.DENGDING]
        for octave in (1, 2)
        for effect in [Stroke.OPEN, Stroke.MUTED, Stroke.GRACE_NOTE, PatternType.TREMOLO]
        for duration in (1.0, 0.5, 0.33, 0.25, 0.0)
        for autogenerated in (None, True, False)
    ]
    # fmt: off
    # pylint: disable=line-too-long
    # Any combination of values from VALID_PITCH_OCTAVE, VALID_STROKE_DURATION and VALID_PITCH_EFFECT for a given position is valid.

    # Valid combinations of pitch and octave attribute values
    VALID_PITCH_OCTAVE = {
        InstrumentGroup.SEMAR_PAGULINGAN: {
            Position.PEMADE_POLOS: [(Pitch.DING, 1), (Pitch.DONG, 1), (Pitch.DENG, 1), (Pitch.DEUNG, 1), (Pitch.DUNG, 1), (Pitch.DANG, 1), (Pitch.DAING, 1)],
            Position.JEGOGAN: [(Pitch.DING, 1), (Pitch.DONG, 1), (Pitch.DENG, 1), (Pitch.DEUNG, 1), (Pitch.DUNG, 1), (Pitch.DANG, 1), (Pitch.DAING, 1)],
            Position.REYONG_1: [],
        },
        InstrumentGroup.GONG_KEBYAR: {
            Position.PEMADE_POLOS: [ (Pitch.DONG, 0), (Pitch.DENG, 0), (Pitch.DUNG, 0), (Pitch.DANG, 0), (Pitch.DING, 1), (Pitch.DONG, 1),  
                                    (Pitch.DENG, 1), (Pitch.DUNG, 1), (Pitch.DANG, 1), (Pitch.DING, 2)],
            Position.JEGOGAN: [(Pitch.DING, 1), (Pitch.DONG, 1), (Pitch.DENG, 1), (Pitch.DUNG, 1), (Pitch.DANG, 1)],
            Position.REYONG_1: [(Pitch.DENG, 0), (Pitch.DUNG, 0), (Pitch.DANG, 0), (Pitch.DING, 1), (Pitch.DONG, 1), (Pitch.DENGDING, 0), (Pitch.STRIKE, None),
                                (Pitch.BYONG, None)],
        },
    }
    ANY = "any"
    # Valid combinations of pitch and effect attribute values
    VALID_PITCH_EFFECT = {
        InstrumentGroup.SEMAR_PAGULINGAN: {
            Position.PEMADE_POLOS: list(product([Pitch.DING, Pitch.DONG, Pitch.DENG, Pitch.DEUNG,Pitch.DUNG, Pitch.DANG, Pitch.DAING], 
                                                [Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED, Stroke.GRACE_NOTE, PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING, PatternType.NOROT])),
            Position.JEGOGAN: list(product([Pitch.DING, Pitch.DONG, Pitch.DENG, Pitch.DEUNG,Pitch.DUNG, Pitch.DANG, Pitch.DAING], 
                                                [Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED, PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING])),
            Position.REYONG_1: [],
        },
        InstrumentGroup.GONG_KEBYAR: {
            Position.PEMADE_POLOS: list(product([Pitch.DING, Pitch.DONG, Pitch.DENG, Pitch.DUNG, Pitch.DANG], 
                                                [Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED, Stroke.GRACE_NOTE, PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING, PatternType.NOROT])),
            Position.JEGOGAN: list(product([Pitch.DING, Pitch.DONG, Pitch.DENG, Pitch.DUNG, Pitch.DANG], 
                                                [Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED, PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING])),
            Position.REYONG_1: list(product([Pitch.DENG, Pitch.DUNG, Pitch.DANG, Pitch.DING, Pitch.DONG], 
                                                [Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED, Stroke.GRACE_NOTE, PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING, PatternType.NOROT])),
        },
    }
    # Valid combinations of effect, duration and autogenerated attribute values
    VALID_EFFECT_DURATIONS_AUTOGEN=(list(product([Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED], [1.0, 0.5, 0.25], [True, False, None])) +
                                    list(product([Stroke.OPEN, Stroke.ABBREVIATED, Stroke.MUTED], [0.33, 0.0], [True])) +
                            list(product([Stroke.GRACE_NOTE], [0.0], [True, False, None])) +
                            list(product([PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING, PatternType.NOROT], [1.0], [True, False, None])) +
                            list(product([PatternType.TREMOLO, PatternType.TREMOLO_ACCELERATING, PatternType.NOROT], [0.5, 0.33, 0.25, 0.0], [True]))
                            )
    # fmt: on

    @classmethod
    def is_valid_combination(cls, group: InstrumentGroup, combination: dict[str, Any]) -> bool:
        """Determines the expected validity of a combination from TRY_COMBINATIONS by comparing its values
           with VALID_PITCH_OCTAVE and VALID_STROKE_DURATION and VALID_EFFECT_DURATIONS_AUTOGEN
        Args:
            group (InstrumentGroup):
            combination (dict[str, Any]): combination of pitch, octave and effect given as a record str->value
        """
        position = combination[NoteFields.POSITION]
        valid_pitch_octave = (
            combination[Note.Fields.PITCH],
            combination[Note.Fields.OCTAVE],
        ) in cls.VALID_PITCH_OCTAVE[group][position]
        valid_pitch_effect = (
            combination[Note.Fields.PITCH],
            combination[Note.Fields.EFFECT],
        ) in cls.VALID_PITCH_EFFECT[group][position]
        valid_duration = (
            combination[Note.Fields.EFFECT],
            combination[Note.Fields.NOTE_VALUE],
            combination[Note.Fields.AUTOGENERATED],
        ) in cls.VALID_EFFECT_DURATIONS_AUTOGEN
        return valid_pitch_octave and valid_pitch_effect and valid_duration

    def test_returns_only_valid_notes(self):
        """Tests each combination in TRY_COMBINATIONS. Check that only Note objects with valid combinations
        of attributes can be created. Any invalid combination should raise an exception.
        """
        for group in [InstrumentGroup.GONG_KEBYAR, InstrumentGroup.SEMAR_PAGULINGAN]:
            self.load_settings(group)
            for combination in self.TRY_COMBINATIONS:
                with self.subTest(combination=list(combination.values())):
                    if self.is_valid_combination(group, combination):
                        try:
                            self.assertIsNotNone(NoteFactory.create_note(**combination))
                        except ValueError:
                            self.fail("Unexpected failure for a valid combination.")
                    else:
                        self.assertRaises(ValueError, NoteFactory.create_note, **combination)


class ToneTester(BaseUnitTestCase):

    def load_settings_sp(self):
        # Create mock notation and converter for semar pagulingan score
        Settings.get(notation_id="test-semarpagulingan", part_id="full")

    def load_settings_gk(self):
        # Create mock notation and converter for gong kebyar score with beat at end
        Settings.get(notation_id="test-gongkebyar", part_id="full")

    # fmt: off
    tone_range_data = [
        # tone, position, expected result of get_kempyung_tones_within_range(tone, position, extended_range, exact_match)
        # expected = results for ([extended_range, exact_match] for extended_range, exact_match in (True, True), (True, False) (False, True), (False, False))
        (Tone(pitch=Pitch.DONG, octave=1), Position.PEMADE_POLOS, 
            ([Tone(pitch=Pitch.DONG, octave=1)], [Tone(pitch=Pitch.DONG, octave=1), Tone(pitch=Pitch.DONG, octave=0)], [Tone(pitch=Pitch.DONG, octave=1)], [Tone(pitch=Pitch.DONG, octave=1), Tone(pitch=Pitch.DONG, octave=0),])
        ),
        (Tone(pitch=Pitch.DONG, octave=2), Position.REYONG_2, ([], [Tone(pitch=Pitch.DONG, octave=1)], [],[Tone(pitch=Pitch.DONG, octave=1)])),
        (Tone(pitch=Pitch.DONG, octave=2), Position.REYONG_3, ([Tone(pitch=Pitch.DONG, octave=2)], [Tone(pitch=Pitch.DONG, octave=2)], [], []))
    ]
    # fmt: on

    def test_get_tones_within_range(self):
        self.load_settings_gk()
        for tone, position, expected in self.tone_range_data:
            with self.subTest(tone=tone, position=position):
                for i, (extended_range, match_octave) in enumerate(product([True, False], [True, False])):
                    self.assertEqual(
                        Instrument.get_tones_within_range(tone, position, extended_range, match_octave), expected[i]
                    )


class RuleTester(BaseUnitTestCase):

    def setUp(self):
        # Create mock notation and converter for gong kebyar score with beat at end
        Settings.get(notation_id="test-gongkebyar", part_id="full")

    # fmt: off
    kempyung_tone_data = [
        # tone, position, expected result of get_kempyung_tones_within_range(tone, position, extended_range, exact_match)
        # expected = results for ([extended_range, exact_match] for extended_range, exact_match in (True, True), (True, False) (False, True), (False, False))
        [Tone(pitch=Pitch.DONG, octave=1), Position.PEMADE_SANGSIH, ([Tone(pitch=Pitch.DANG, octave=1)], [Tone(pitch=Pitch.DANG, octave=1), Tone(pitch=Pitch.DANG, octave=0)], [Tone(pitch=Pitch.DANG, octave=1)], [Tone(pitch=Pitch.DANG, octave=1), Tone(pitch=Pitch.DANG, octave=0)])],
        [Tone(pitch=Pitch.DUNG, octave=0), Position.PEMADE_SANGSIH, ([Tone(pitch=Pitch.DONG, octave=1)], [Tone(pitch=Pitch.DONG, octave=1), Tone(pitch=Pitch.DONG, octave=0)],[Tone(pitch=Pitch.DONG, octave=1)],[Tone(pitch=Pitch.DONG, octave=1), Tone(pitch=Pitch.DONG, octave=0)])],
        [Tone(pitch=Pitch.DANG, octave=1), Position.PEMADE_SANGSIH, ([], [Tone(pitch=Pitch.DENG, octave=1), Tone(pitch=Pitch.DENG, octave=0)], [], [Tone(pitch=Pitch.DENG, octave=1), Tone(pitch=Pitch.DENG, octave=0)])],
        [Tone(pitch=Pitch.DANG, octave=1), Position.REYONG_2, ([], [Tone(pitch=Pitch.DENG, octave=1)], [], [Tone(pitch=Pitch.DENG, octave=1)])],
        [Tone(pitch=Pitch.DING, octave=2), Position.REYONG_2, ([], [Tone(pitch=Pitch.DUNG, octave=1)], [], [])],
        [Tone(pitch=Pitch.DENG, octave=0), Position.REYONG_2, ([Tone(pitch=Pitch.DING, octave=1)], [Tone(pitch=Pitch.DING, octave=1)],[Tone(pitch=Pitch.DING, octave=1)], [Tone(pitch=Pitch.DING, octave=1)])]
    ]
    # fmt: on

    def test_get_kempyung_tones(self):
        for tone, position, expected in self.kempyung_tone_data:
            for i, (extended_range, exact_match) in enumerate(product([True, False], [True, False])):
                with self.subTest(tone=tone, position=position, extended_range=extended_range, exact_match=exact_match):
                    self.assertEqual(
                        RuleCastToPosition.get_kempyung_tones_within_range(tone, position, extended_range, exact_match),
                        expected[i],
                    )

    data_shared_notation_rule = [
        (
            Position.PEMADE_SANGSIH,
            GenericNote(symbol="u", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {Position.PEMADE_SANGSIH, Position.KANTILAN_SANGSIH},
            [RuleValue.SAME_TONE],
        ),
        (
            Position.PEMADE_SANGSIH,
            GenericNote(symbol="u", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {Position.PEMADE_POLOS, Position.PEMADE_SANGSIH},
            [RuleValue.EXACT_KEMPYUNG, RuleValue.SAME_TONE, RuleValue.SAME_PITCH],
        ),
        (
            Position.PEMADE_SANGSIH,
            # Rake pattern pitch should not be cast to kempyung
            GenericNote(symbol="u", pitch=Pitch.DONG, octave=1, effect=PatternType.RAKE_LEFT),
            {Position.PEMADE_POLOS, Position.PEMADE_SANGSIH},
            [RuleValue.SAME_TONE, RuleValue.SAME_PITCH],
        ),
        (
            Position.PEMADE_SANGSIH,
            GenericNote(symbol="u", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {Position.UGAL, Position.PEMADE_SANGSIH},
            [RuleValue.EXACT_KEMPYUNG, RuleValue.SAME_TONE, RuleValue.SAME_PITCH],
        ),
        (
            Position.REYONG_3,
            GenericNote(symbol="u", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {Position.REYONG_1, Position.REYONG_2, Position.REYONG_3, Position.REYONG_4},
            [RuleValue.SAME_PITCH, RuleValue.KEMPYUNG],
        ),
        (
            Position.REYONG_3,
            GenericNote(symbol="u", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {
                Position.PEMADE_POLOS,
                Position.PEMADE_SANGSIH,
                Position.REYONG_1,
                Position.REYONG_2,
                Position.REYONG_3,
                Position.REYONG_4,
            },
            [RuleValue.SAME_PITCH, RuleValue.KEMPYUNG],
        ),
        (
            Position.REYONG_3,
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {Position.REYONG_1, Position.REYONG_3},
            [RuleValue.SAME_PITCH_EXTENDED_RANGE],
        ),
        (
            Position.UGAL,
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            {
                Position.UGAL,
                Position.PEMADE_POLOS,
                Position.PEMADE_SANGSIH,
                Position.KANTILAN_POLOS,
                Position.KANTILAN_SANGSIH,
            },
            [RuleValue.SAME_TONE, RuleValue.SAME_PITCH],
        ),
    ]

    def test_shared_notation_rule(self):
        for position, note, all_positions, expected in self.data_shared_notation_rule:
            with self.subTest(position=position, note=note, all_positions=all_positions):
                self.assertEqual(RuleCastToPosition.get_casting_rule(position, note, all_positions), expected)

    P_POLOS = Position.PEMADE_POLOS
    P_SANGSIH = Position.PEMADE_SANGSIH
    K_POLOS = Position.KANTILAN_POLOS
    K_SANGSIH = Position.KANTILAN_SANGSIH
    GANGSA = {P_POLOS, P_SANGSIH, K_POLOS, K_SANGSIH}
    R_1 = Position.REYONG_1
    R_2 = Position.REYONG_2
    R_3 = Position.REYONG_3
    R_4 = Position.REYONG_4
    REYONG = {R_1, R_2, R_3, R_4}

    data_shared_notation = [
        [
            GenericNote(symbol="o,", pitch=Pitch.DONG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DANG, octave=0, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="o,", pitch=Pitch.DONG, octave=0, effect=PatternType.TREMOLO),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DANG, octave=0, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=0, effect=PatternType.RAKE_LEFT),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DONG, octave=0, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=0, effect=PatternType.RAKE_LEFT),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DONG, octave=0, transformation=RuleValue.SAME_TONE),
        ],
        [
            # 5
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DING, octave=1, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DONG, octave=1, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DENG, octave=1, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DUNG, octave=1, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            # 10
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.EXACT_KEMPYUNG),
        ],
        [
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DUNG, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=2, effect=Stroke.OPEN),
            P_SANGSIH,
            GANGSA,
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="o,", pitch=Pitch.DONG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DONG, octave=0, transformation=RuleValue.SAME_TONE),
        ],
        [
            # 15
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DENG, octave=0, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DUNG, octave=0, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DANG, octave=0, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DING, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DONG, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            # 20
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DENG, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DUNG, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=1, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=2, effect=Stroke.OPEN),
            P_SANGSIH,
            {K_SANGSIH, P_SANGSIH},
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.SAME_TONE),
        ],
        [
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            R_1,
            REYONG,
            Tone(pitch=Pitch.DENG, octave=0, transformation=RuleValue.SAME_PITCH),
        ],
        [
            # 25
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            R_1,
            REYONG,
            Tone(pitch=Pitch.DUNG, octave=0, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            R_1,
            REYONG,
            Tone(pitch=Pitch.DANG, octave=0, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            R_1,
            REYONG,
            Tone(pitch=Pitch.DUNG, octave=0, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            R_1,
            REYONG,
            Tone(pitch=Pitch.DANG, octave=0, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            R_2,
            REYONG,
            Tone(pitch=Pitch.DENG, octave=1, transformation=RuleValue.SAME_PITCH),
        ],
        [
            # 30
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            R_2,
            REYONG,
            Tone(pitch=Pitch.DONG, octave=1, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            R_2,
            REYONG,
            Tone(pitch=Pitch.DENG, octave=1, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            R_2,
            REYONG,
            Tone(pitch=Pitch.DING, octave=1, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            R_2,
            REYONG,
            Tone(pitch=Pitch.DONG, octave=1, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            R_3,
            REYONG,
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.KEMPYUNG),
        ],
        [
            # 35
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            R_3,
            REYONG,
            Tone(pitch=Pitch.DUNG, octave=1, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            R_3,
            REYONG,
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            R_3,
            REYONG,
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            R_3,
            REYONG,
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            R_3,
            {R_1, R_3},
            Tone(pitch=Pitch.DENG, octave=1, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            # 40
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            R_3,
            {R_1, R_3},
            Tone(pitch=Pitch.DUNG, octave=1, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            R_3,
            {R_1, R_3},
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            R_3,
            {R_1, R_3},
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            R_3,
            {R_1, R_3},
            Tone(pitch=Pitch.DONG, octave=2, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            R_4,
            REYONG,
            Tone(pitch=Pitch.DENG, octave=2, transformation=RuleValue.SAME_PITCH),
        ],
        [
            # 45
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            R_4,
            REYONG,
            Tone(pitch=Pitch.DUNG, octave=2, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            R_4,
            REYONG,
            Tone(pitch=Pitch.DENG, octave=2, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            R_4,
            REYONG,
            Tone(pitch=Pitch.DUNG, octave=2, transformation=RuleValue.KEMPYUNG),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            R_4,
            REYONG,
            Tone(pitch=Pitch.DONG, octave=2, transformation=RuleValue.SAME_PITCH),
        ],
        [
            GenericNote(symbol="e", pitch=Pitch.DENG, octave=0, effect=Stroke.OPEN),
            R_4,
            {R_2, R_4},
            Tone(pitch=Pitch.DENG, octave=2, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            # 50
            GenericNote(symbol="u", pitch=Pitch.DUNG, octave=0, effect=Stroke.OPEN),
            R_4,
            {R_2, R_4},
            Tone(pitch=Pitch.DUNG, octave=2, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="a", pitch=Pitch.DANG, octave=0, effect=Stroke.OPEN),
            R_4,
            {R_2, R_4},
            Tone(pitch=Pitch.DANG, octave=1, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="i", pitch=Pitch.DING, octave=1, effect=Stroke.OPEN),
            R_4,
            {R_2, R_4},
            Tone(pitch=Pitch.DING, octave=2, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
        [
            GenericNote(symbol="o", pitch=Pitch.DONG, octave=1, effect=Stroke.OPEN),
            R_4,
            {R_2, R_4},
            Tone(pitch=Pitch.DONG, octave=2, transformation=RuleValue.SAME_PITCH_EXTENDED_RANGE),
        ],
    ]

    def test_apply_casting_rule(self):
        for counter, (note, position, all_positions, expected) in enumerate(self.data_shared_notation, start=1):
            with self.subTest(nr=counter, note=note, position=position, all_positions=all_positions):
                cast_tone = RuleCastToPosition.cast_to_position(
                    note=note, position=position, all_positions=all_positions, metadata=[]
                )
                self.assertEqual(cast_tone, expected)
