---
notation:
  composition: rejangdewa
instruments: 
  instrumentgroup: GONG_KEBYAR
midi:
  midiversion: GONG_KEBYAR1
samples:
  instrumentgroup: GONG_KEBYAR
switches:
  validate_settings : true
  detailed_validation_logging : false
  autocorrect : true
  save_corrected_to_file : true
  create_midifile : true
