---
# The settings below (except for options) refer to values in the data.yaml file.
# The font selection is defined in the details of the selected notation component (see data.yaml file).
instruments: 
  instrumentgroup: GONG_KEBYAR
midi:
  midiversion: GONG_KEBYAR3
samples:
  instrumentgroup: GONG_KEBYAR
notation:
  composition: preset-test
soundfont:
  definition_file_out: viena_definitions_${midi.midiversion}.txt
  soundfont_file_out: ${midi.midiversion}.sf2
  soundfont_destination_folders:
    - ~/Documents/SynthFont
    - ~/Documents/administratie/_VRIJETIJD_REIZEN/Scripts-Programmas/JavaScriptProjects/midi-player/data/soundfont
options:
  validate_settings : true
  notation_to_midi:
    run: true
    detailed_validation_logging : false
    autocorrect : true
    save_corrected_to_file : false
    create_midifile : true
  soundfont:
    run: true
    create_sf2_files: true
