---
composition: rejangdewa
midi:
  version: MULTIPLE_INSTR
  midi_definition_file: midinotes.tsv
  presets_file: presets.tsv
instruments_file: instruments.tsv
instrumenttags_file: instrumenttags.tsv
validate_settings : true
detailed_validation_logging : false
autocorrect : true
save_corrected_to_file : true
create_midifile : true
