---
composition: rejangdewa
midinotes_file: midinotes.tsv
midi_version: midi-gk2
instruments_file: instruments.tsv
instrumenttags_file: instrumenttags.tsv
validate_settings : true
detailed_validation_logging : false
autocorrect : true
save_corrected_to_file : true
create_midifile : true
