(*
@@grammar::FONT

@@whitespace :: None

start = beat $ ;

A COMPLETE VALIDATION OF THE MUSIC NOTATION WITH TATSU IS TOO RUNTIME INTENSIVE.
THEREFORE ONLY A BASIC VALIDITY CHECK IS PERFORMED HERE.
*)

(* A note consists of a pitch symbol followed by one or more modifiers *)
(* This definition splits the notation into separate 'note' strings *)
note = /[\(\)\*-\.089ABEGIOPSTUXabeinorstuxy][,\/:;<=\?_\[\]]*/ ;
