(*
@@grammar::METADATA

start
    =
    "{"
    @:metadata 
    "}"
    $
    ;
*)

metadata
    =
    @:(dynamicsmeta |
        gonganmeta |
        gotometa |
        kemplimeta |
        autokempyungmeta |
        labelmeta |
        loopmeta |
        octavatemeta |
        partmeta |
        repeatmeta |
        sequencemeta |
        suppressmeta |
        tempometa |
        copymeta |
        validationmeta |
        waitmeta)
  ;

copymeta = metatype:'COPY' {('template' | 'value') '='} template:strvalue ['include' '=' include:strlistvalue];

dynamicsmeta = metatype:'DYNAMICS' {'value' '='} range_values:dynamics_range parameters:dynamicsmetaparameters ;
dynamicsmetaparameters ={[','] @:(beat_range_parm | beat_count_parm | first_beat_parm | passes_parm | cycle_parm | iterations_parm | positions_parm)} ;

gonganmeta = metatype:'GONGAN' {('type'|'value') '='} type:strvalue ;
    
gotometa = metatype:'GOTO' {('label'|'value') '='} label:alphanumvalue parameters:gotometaparameters ;
gotometaparameters = {[','] @:(from_beat_parm | passes_parm | cycle_parm)} ;

kemplimeta = metatype:'KEMPLI' {('status'|'value') '='} status:alphavalue parameters:kemplimetaparameters ;
kemplimetaparameters = {[','] @:(beats_parm | scope_parm | passes_parm)} ;

autokempyungmeta = metatype:'AUTOKEMPYUNG' {('status'|'value') '='} status:alphavalue parameters:autokempyungmetaparameters ;
autokempyungmetaparameters = {[','] @:(scope_parm | positions_parm)} ;

labelmeta = metatype:'LABEL' {('name'|'value') '='} name:alphanumvalue parameters:labelmetaparameters ;
labelmetaparameters = {[','] @:beat_parm} ;
    
loopmeta = metatype:'LOOP' {('count'|'value') '='} count:intvalue ;
    
octavatemeta = metatype:'OCTAVATE' {('instrument'|'value') '='} instrument:strvalue parameters:octavatemetaparameters ;
octavatemetaparameters = {[','] @:(octaves_parm | scope_parm)} ;

partmeta = metatype:'PART' {('name'|'value') '='} name:alphanumvalue ;
    
repeatmeta = metatype:'REPEAT' {('count'|'value') '='} count:intvalue ;
    
sequencemeta = metatype:'SEQUENCE' {'value' '='} value:strlistvalue_multiline ;
    
suppressmeta = metatype:'SUPPRESS' {('positions'|'value') '='} (positions+:strvalue | positions:strlistvalue)  parameters:suppressmetaparameters ;
suppressmetaparameters = {[','] @:(beats_parm | passes_parm)} ;

tempometa = metatype:'TEMPO' {'value' '='} range_values:tempo_range  parameters:tempometaparameters ;
tempometaparameters = {[','] @:(beat_range_parm | beat_count_parm | first_beat_parm | passes_parm | iterations_parm | cycle_parm)} ;

validationmeta = metatype:'VALIDATION' {('ignore'|'value') '='} (ignore:strlistvalue | ignore+:strvalue) parameters:validationmetaparameters ;
validationmetaparameters = {[','] @:(beats_parm | scope_parm)} ;

waitmeta = metatype:'WAIT' {('seconds'|'value') '='} seconds:floatvalue parameters:waitmetaparameters ;
waitmetaparameters = {[','] @:(after_parm | passes_parm)};

after_parm = 'after' '=' after:boolvalue;
beat_count_parm = 'beat_count' '=' beat_count:intvalue;
beat_parm = 'beat' '=' beat:intvalue;
beats_parm = ('beats' | 'beat') '=' (beats+:intvalue | beats:intlistvalue);
beat_range_parm = ('beats' | 'beat') '=' first_beat:intvalue [("->" explicit_gradual_beat:`true`) last_beat:intvalue] ;
cycle_parm = 'cycle' '=' cycle:intvalue;
(* dynamics_range can have format 'mf', 'p->mf' or '->mf' *)
dynamics_range = [from_abbr:dynamics_value "->" explicit_gradual_value:`true` | "->" explicit_gradual_value:`true`] to_abbr:dynamics_value;
dynamics_value = 'pp' | 'p' | 'mp' | 'mf' | 'f' | 'ff';
first_beat_parm = ('first_beat' | 'beat') '=' first_beat:intvalue;
from_beat_parm = 'from_beat' '=' from_beat:intvalue;
octaves_parm = 'octaves' '=' octaves:intvalue;
passes_parm = ('passes' | 'pass') '=' (passes+:intvalue | passes:intlistvalue);
(* tempo_range can have format '150', '100->150' or '->150' *)
tempo_range = [from_value:intvalue "->" explicit_gradual_value:`true` | "->" explicit_gradual_value:`true`] to_value:intvalue;
iterations_parm = ('iterations' | 'iteration') '=' (iterations+:intvalue | iterations:intlistvalue);
positions_parm = ('positions' | 'position') '=' (positions+:strvalue | positions:strlistvalue);
scope_parm = 'scope' '=' scope:strvalue;
