eol = /\n/ | /\r\n/ | $ ;
tab = /\t/ ;
alphavalue = (nqstrvalue | sqstrvalue | dqstrvalue) ;
nqalphavalue = /[a-zA-Z_][\w\-]*/ ;      (* unquoted string *)
sqalphavalue = "'" @:/([a-zA-Z_][\w\- ]*)/ "'"; (* single-quoted string *)
dqalphavalue = '"' @:/([a-zA-Z_][\w\- ]*)/ '"'; (* double-quoted string *)
alphanumvalue = (nqalphanumvalue | sqalphanumvalue | dqalphanumvalue) ;
nqalphanumvalue = /[\d\w\+\-\\&]+/ ;      (* unquoted string *)
sqalphanumvalue = "'" @:/([\d\w\+\-\\& ]+)/ "'"; (* single-quoted string *)
dqalphanumvalue = '"' @:/([\d\w\+\-\\& ]+)/ '"'; (* double-quoted string *)
strvalue = (nqstrvalue | sqstrvalue | dqstrvalue) ;
nqstrvalue = /[^\t\r\n'", \(\)\[\]\{\}]+/ ;      (* unquoted string *)
sqstrvalue = "'" @:/[^\t\r\n']+/ "'" ; (* single-quoted string *)
dqstrvalue = '"' @:/[^\t\r\n"]+/ '"' ; (* double-quoted string *)
numvalue = intvalue | floatvalue ;
intvalue = /\d+/ ;
floatvalue = /\d+\.{0,1}\d*/ ;
boolvalue = 'true' | 'false' ;
alphalistvalue = '[' @+:alphavalue {',' @+:alphavalue}* ']' ;
alphanumlistvalue = '[' @+:alphanumvalue {',' @+:alphanumvalue}* ']' ;
strlistvalue = '[' @+:strvalue {',' @+:strvalue}* ']' ;
sp_nl = /(?m)[ \t\n\r]*/ ;  (* Extended space, including new line. (?m) allows multiline parsing. Default is single line *)
strlistvalue_multiline = '[' @+:strvalue {sp_nl ',' sp_nl @+:strvalue}* sp_nl ']' ;
intlistvalue = '[' @+:intvalue {',' @+:intvalue}* ']' ;
