---
# Configuration file of the gamelan-notation application.
# The folder and file names in the `instruments`, `midi`, `font`, `grammar` and `pdf_converter` sections refer to subfolders of the `settings` folder.
# All other sections refer to subfolders and files in the `data` folder.

instruments: 
    folder: ./config/instruments
    instruments_file: instruments.tsv
    tags_file: instrumenttags.tsv
    rules_file: rules.tsv
    # shorthand_notation: instruments for which silence and extension symbols may be omitted
    shorthand_notation: [UGAL, CALUNG, PENYACAH, JEGOGAN, GONGS, KEMPLI]
midi:
    folder: ./config/midi
    midi_definition_file: gamelan_midinotes1.tsv
    presets_file: gamelan_presets1.tsv
    midiversion: GAMELAN1
    # PPQ (pulses per quarternote) and base_note_time in MIDI ticks. Beat is MIDI beat, not kempli beat.
    # beat indication (BPM) in notations should be expressed in MIDI beats.
    PPQ: 96
    base_note_time: 24
    base_notes_per_beat: 4
    dynamics:
        ff: 127
        f: 105
        mf: 85
        mp: 65
        p: 45
        pp: 30
    default_dynamics: mf
    silence_seconds_before_start: 3 
    silence_seconds_after_end: 10
    tremolo:
        # TREMOLO
        # notes_per_quarternote -  tremolo frequency (number of beats per time unit). Should be a divisor of base_note_time.
        # The tremolo respects the note duration, i.e. a tremolo of one base note will last for `base_note_time` duration.
        # The duration of the tremolo can be extended by adding consecutive tremolo notes. This will not alter the tremolo frequency.
        # ACCELERATING TREMOLO
        # The duration and beat frequencies of this type of tremolo is currently fixed and is independent of the number of base notes.
        # The effect of two consecutive tremolo notes is that these notes will be alternated throughout the pattern.
        # e.g. consecutive acc tremolo notes DONG and DENG will result in a pattern DONG-DENG-DONG-DENG etc. with as many notes as the 
        # length of `accelerating_pattern`. The total duration will be the same as the duration of a single acc tremolo note.
        # accelerating_pattern - relative duration of the notes in midi ticks. E.g. if base_note_time=24, then 24 is a standard note duration.
        #                        The list should contain an even number of values so that alternating note patterns end on the second note.
        # accelerating_velocity - MIDI velocity value (0-127) for each note. The number of values should match that of `accelerating_pattern`.
        notes_per_quarternote: 3
        accelerating_pattern: [48, 40, 32, 26, 22, 18, 14, 10, 10, 10, 10, 10]
        accelerating_velocity: [100, 100, 100, 100, 100, 100, 100, 90, 80, 70, 60, 50]
notation:
    gongantypes_without_kempli: [KEBYAR, GINEMAN, GENDERAN]
font:
    folder: ./config/font
    file: balimusic5font.tsv
    ttf_file: bali-music-5.ttf
grammar:
    folder: ./config/grammars
    notationfile: notation.ebnf
    metadatafile: metadata.ebnf
    picklefile: notation_model.pickle
    fontfile: font5.ebnf
pdf_converter:
    folder: ./config/pdf_converter
    # Date format in PDF document header
    version_fmt: "%d-%b-%Y"
    fonts:
        Courier New: COUR.TTF
        Arial: ARIBLK.TTF
        BaliMusic5: bali-music-5.ttf
    notation_webpage: https://swarasanti.nl/music-notation/
    # Do not print octave diacritics, as they are redundant for these positions
    omit_octave_diacritics: [REYONG_1, REYONG_2, REYONG_3, REYONG_4]
samples:
    folder: ./data/samples
    subfolder: gamelan
soundfont:
    folder: ./data/soundfont
    path_to_viena_app: C:/Program Files/Viena/Viena64.exe
midiplayer:
    folder: ./data/midiplayer
    contentfile: content.json
    helpinghand: [CALUNG, PENYACAH, JEGOGAN, PEMADE_POLOS, PEMADE_SANGSIH, KANTILAN_POLOS, KANTILAN_SANGSIH, UGAL] # Animate panggul.
notationfiles:
    # `beat_at_end` indicates whether the notation has the gir at the end of each gongan (Balinese concept) or at the beginning.
    # `beat_at_end` notation will be converted to beat at beginning.
    # If `loop`==false, the last note of each instrument will be extended for a natural fade out.
    # Otherwise the midi file will end abruptly to allow looping.
    defaults:
        instrumentgroup: GONG_KEBYAR
        folder_in: ./data/notation/${{_PARENT_.subfolder}}
        # Formatting for version id, using last modification date of the input file.
        version_fmt: "%d-%b-%Y"
        folder_out_nonprod: ./data/notation/${{_PARENT_.subfolder}}
        folder_out_prod: ${{midiplayer.folder}}
        midi_out_file_pattern: !!str "${{_PARENT_.title}}_{part_id}_${{midi.midiversion}}.mid"
        pdf_out_file_pattern: !!str "${{_PARENT_.title}}_{part_id}_${{midi.midiversion}}.pdf"
        # part for which to generate a PDF notation document
        generate_pdf_part_id: full
        beat_at_end: false
        autocorrect_kempyung : true
        fontversion: BaliMusic5
        include_in_run_types: [RUN_SINGLE, RUN_ALL]
        include_in_production_run: true
    bapangselisir:
        title: Bapang Selisir
        subfolder: bapang selisir
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            full:
                name: entire piece
                file: Bapang Selisir_font5.tsv
                loop: false
    bapangselisir-gk:
        title: Bapang Selisir (gong kebyar)
        subfolder: bapang selisir
        instrumentgroup: GONG_KEBYAR
        include_in_production_run: false
        parts:
            full:
                name: entire piece
                file: Bapang Selisir_font5_GK.tsv
                loop: false
    cendrawasih:
        title: Cendrawasih
        subfolder: cendrawasih
        parts:
            full:
                name: entire piece
                file: Cendrawasih_complete_font5.tsv
                loop: false
    gilakdeng:
        title: Gilak Deng
        subfolder: gilak deng
        parts:
            full:
                name: entire piece
                file: Gilak Deng.tsv
                loop: false
            kotekan:
                name: kotekan gangsa
                file: Gilak Deng_kotekan_gangsa.tsv
                loop: true
    godekmiring:
        title: Godek Miring
        subfolder: godek miring
        instrumentgroup: SEMAR_PAGULINGAN
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Godek miring font5.tsv
                loop: false
            kawitan:
                name: kawitan (no angsel)
                file: Godek Miring font5_kawitan.tsv
                loop: true
            kawitan-angsel: 
                name: kawitan (with angsel)
                file: Godek Miring font5_kawitan with angsel.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Godek Miring font5_pengecet.tsv
                loop: true
            pengawak:
                name: pengawak
                file: Godek Miring font5_pengawak.tsv
                loop: true
    janger:
        title: Janger
        subfolder: janger
        parts:
            full:
                name: entire piece
                file: Janger.tsv
                loop: false
    kahyangan:
        title: Kahyangan (dance improv.)
        subfolder: kahyangan
        parts:
            full:
                name: entire piece
                file: Kahyangan_font5.tsv
                loop: false
    legongmahawidya:
        title: Legong Mahawidya SP
        subfolder: legong mahawidya
        production: false
        parts:
            full:
                name: entire piece
                file: Legong Mahawidya_font5_SP.tsv
                loop: false
    legongmahawidya-gk:
        title: Legong Mahawidya GK
        subfolder: legong mahawidya
        parts:
            full:
                name: entire piece
                file: Legong Mahawidya_font5_GK.tsv
                loop: false
            kawitan:
                name: kawitan
                file: Legong Mahawidya_font5_GK_kawitan.tsv
                loop: true
            pengawak:
                name: pengawak
                file: Legong Mahawidya_font5_GK_pengawak.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Legong Mahawidya_font5_GK_pengecet.tsv
                loop: true
    lengker:
        title: Lengker
        subfolder: lengker
        autocorrect_kempyung : false
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            full:
                name: entire piece
                file: Lengker Ubud font5.tsv
                loop: false
            kawitan:
                name: kawitan
                file: Lengker Ubud font5_kawitan.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Lengker Ubud font5_pengecet.tsv
                loop: true
            pengawak:
                name: pengawak
                file: Lengker Ubud font5_pengawak.tsv
                loop: true
    lengker-gk:
        title: Lengker (gong kebyar)
        subfolder: lengker
        autocorrect_kempyung : false
        instrumentgroup: GONG_KEBYAR
        include_in_production_run: false
        parts:
            full:
                name: entire piece
                file: Lengker Ubud font5_GK.tsv
                loop: false
    margapati:
        title: Margapati
        subfolder: margapati
        parts:
            full:
                name: entire piece
                file: Margapati_font5.tsv
                loop: false
    merahputih:
        title: Merah Putih
        subfolder: merah putih
        parts:
            full:
                name: entire piece (loop)
                file: Merah Putih.tsv
                loop: true
    pendet:
        title: Pendet
        subfolder: pendet
        beat_at_end: true
        parts:
            full:
                name: entire piece
                file: pendet_font5_beat_at_end.tsv
                loop: false
    puspamekar:
        title: Puspa Mekar
        subfolder: puspa mekar
        parts:
            full:
                name: entire piece
                file: Puspa Mekar.tsv
                loop: false
            kawitan:
                name: kawitan
                file: Puspa Mekar kawitan.tsv
                loop: true
            pengecet1:
                name: pengecet 1
                file: Puspa mekar pengecet1.tsv
                loop: true
    palawakya:
        title: Palawakya (under development)
        subfolder: palawakya
        midi_out_file_pattern: !!str "Palawakya_{part_id}_${{midi.midiversion}}.mid"
        pdf_out_file_pattern: !!str "Palawakya_{part_id}_${{midi.midiversion}}.pdf"
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Palawakya.tsv
                loop: false
    rejangdewa:
        title: Rejang Dewa
        subfolder: rejang dewa
        parts:
            full:
                name: entire piece
                file: rejang dewa_font5.tsv
                loop: false
            intro:
                name: intro
                file: rejang dewa intro_font5.tsv
                loop: true
            pengawak:
                name: pengawak
                file: rejang dewa pengawak_font5.tsv
                loop: true
            pengawak-reyong:
                name: pengawak reyong
                file: rejang dewa pengawak reyong_font5.tsv
                loop: true
            pengecet:
                name: pengecet
                file: rejang dewa pengecet_font5.tsv
                loop: true
        autocorrect_kempyung : false
    sekargendot:
        title: Sekar Gendot
        subfolder: sekar gendot
        instrumentgroup: SEMAR_PAGULINGAN
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Sekar Gendot font5.tsv
                loop: false
    sekargendot-gk:
        title: Sekar Gendot (gong kebyar)
        subfolder: sekar gendot
        instrumentgroup: GONG_KEBYAR
        autocorrect_kempyung : false
        include_in_production_run: false
        parts:
            full:
                name: entire piece
                file: Sekar Gendot font5_GK.tsv
                loop: false
    sinomladrang-sp:
        title: Sinom Ladrang
        subfolder: sinom ladrang
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            full:
                name: entire piece
                file: Sinom Ladrang_SP_font5.tsv
                loop: false
            pengawak:
                name: pengawak
                file: Sinom Ladrang_SP_font5_pengawak.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Sinom Ladrang_SP_font5_pengecet.tsv
                loop: true
    sinomladrang-gk:
        title: Sinom Ladrang (GK)
        subfolder: sinom ladrang
        instrumentgroup: GONG_KEBYAR
        parts:
            full:
                name: entire piece
                file: Sinom Ladrang_GK_ubit4_font5.tsv
                loop: false
    test-gk:
        production: false
        include_in_run_types: [RUN_SINGLE]
        include_in_production_run: false
        title: Test Gong Kebyar
        subfolder: test
        beat_at_end: false            
        instrumentgroup: GONG_KEBYAR
        parts:
            gendinganak2:
                name: gending anak-anak
                file: Gending Anak-Anak.tsv
                loop: false
            cendrawasih:
                name: Cendrawasih
                file: Cendrawasih_complete_font5.tsv
                loop: false
            reyong_13_12:
                name: reyong 1-3, 2-4
                file: reyong13_24_test.tsv
                loop: false
    test-sp:
        production: false
        include_in_run_types: [RUN_SINGLE]
        include_in_production_run: false
        title: Test Semar Pagulingan
        subfolder: test
        beat_at_end: false            
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            sinomladrang:
                name: Sinom Ladrang
                file: Sinom Ladrang_SP_font5.tsv
                loop: false
