---
# Contains information about the input notation files for the notation2midi application.
# All sections refer to subfolders and files in the `data` folder.

notationfiles:
    # `beat_at_end` indicates whether the notation has the gir at the end of each gongan (Balinese concept) or at the beginning.
    # `beat_at_end` notation will be converted to beat at beginning.
    # If `loop`==false, the last note of each instrument will be extended for a natural fade out.
    # Otherwise the midi file will end abruptly to allow looping.
    defaults:
        instrumentgroup: GONG_KEBYAR
        folder_in: ./data/notation/${{_PARENT_.subfolder}}
        # Formatting for version id, using last modification date of the input file.
        version_fmt: "%d-%b-%Y"
        folder_out_nonprod: ./data/notation/${{_PARENT_.subfolder}}
        folder_out_prod: ${{midiplayer.folder}}
        midi_out_file_pattern: !!str "${{_PARENT_.title}}_{part_id}_${{midi.midiversion}}.mid"
        pdf_out_file_pattern: !!str "${{_PARENT_.title}}_{part_id}_${{midi.midiversion}}.pdf"
        # part for which to generate a PDF notation document
        generate_pdf_part_id: full
        beat_at_end: false
        autocorrect_kempyung : true
        fontversion: BaliMusic5
        include_in_run_types: [RUN_SINGLE, RUN_ALL]
        include_in_production_run: true
    bapangselisir:
        title: Bapang Selisir
        subfolder: bapang selisir
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            full:
                name: entire piece
                file: Bapang Selisir_font5.tsv
                loop: false
    bapangselisir-gk:
        title: Bapang Selisir (gong kebyar)
        subfolder: bapang selisir
        instrumentgroup: GONG_KEBYAR
        include_in_production_run: false
        parts:
            full:
                name: entire piece
                file: Bapang Selisir_font5_GK.tsv
                loop: false
    cendrawasih:
        title: Cendrawasih
        subfolder: cendrawasih
        midi_out_file_pattern: !!str "${{_PARENT_.title}}_{part_id}_${{midi.midiversion}}_TEST.mid"
        pdf_out_file_pattern: !!str "${{_PARENT_.title}}_{part_id}_${{midi.midiversion}}_TEST.pdf"
        parts:
            full:
                name: entire piece
                file: Cendrawasih_isi.tsv
                loop: false
    gilakdeng:
        title: Gilak Deng
        subfolder: gilak deng
        parts:
            full:
                name: entire piece
                file: Gilak Deng.tsv
                loop: false
            kotekan:
                name: kotekan gangsa
                file: Gilak Deng_kotekan_gangsa.tsv
                loop: true
    godekmiring:
        title: Godek Miring
        subfolder: godek miring
        instrumentgroup: SEMAR_PAGULINGAN
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Godek miring font5.tsv
                loop: false
            kawitan:
                name: kawitan (no angsel)
                file: Godek Miring font5_kawitan.tsv
                loop: true
            kawitan-angsel: 
                name: kawitan (with angsel)
                file: Godek Miring font5_kawitan with angsel.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Godek Miring font5_pengecet.tsv
                loop: true
            pengawak:
                name: pengawak
                file: Godek Miring font5_pengawak.tsv
                loop: true
    hujanmas:
        title: Hujan Mas
        subfolder: hujan mas
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Hujan Mas.tsv
                loop: false
    janger:
        title: Janger
        subfolder: janger
        parts:
            full:
                name: entire piece
                file: Janger.tsv
                loop: false
    kahyangan:
        title: Kahyangan (dance improv.)
        subfolder: kahyangan
        parts:
            full:
                name: entire piece
                file: Kahyangan_font5.tsv
                loop: false
    legongmahawidya:
        title: Legong Mahawidya SP
        subfolder: legong mahawidya
        production: false
        parts:
            full:
                name: entire piece
                file: Legong Mahawidya_font5_SP.tsv
                loop: false
    legongmahawidya-gk:
        title: Legong Mahawidya GK
        subfolder: legong mahawidya
        parts:
            full:
                name: entire piece
                file: Legong Mahawidya_font5_GK.tsv
                loop: false
            kawitan:
                name: kawitan
                file: Legong Mahawidya_font5_GK_kawitan.tsv
                loop: true
            pengawak:
                name: pengawak
                file: Legong Mahawidya_font5_GK_pengawak.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Legong Mahawidya_font5_GK_pengecet.tsv
                loop: true
    lengker:
        title: Lengker
        subfolder: lengker
        autocorrect_kempyung : false
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            full:
                name: entire piece
                file: Lengker Ubud font5.tsv
                loop: false
            kawitan:
                name: kawitan
                file: Lengker Ubud font5_kawitan.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Lengker Ubud font5_pengecet.tsv
                loop: true
            pengawak:
                name: pengawak
                file: Lengker Ubud font5_pengawak.tsv
                loop: true
    lengker-gk:
        title: Lengker (gong kebyar)
        subfolder: lengker
        autocorrect_kempyung : false
        instrumentgroup: GONG_KEBYAR
        include_in_production_run: false
        parts:
            full:
                name: entire piece
                file: Lengker Ubud font5_GK.tsv
                loop: false
    margapati:
        title: Margapati
        subfolder: margapati
        parts:
            full:
                name: entire piece
                file: Margapati_font5.tsv
                loop: false
    merahputih:
        title: Merah Putih
        subfolder: merah putih
        parts:
            full:
                name: entire piece (loop)
                file: Merah Putih.tsv
                loop: true
    pendet:
        title: Pendet
        subfolder: pendet
        beat_at_end: true
        parts:
            full:
                name: entire piece
                file: pendet_font5_beat_at_end.tsv
                loop: false
    puspamekar:
        title: Puspa Mekar
        subfolder: puspa mekar
        parts:
            full:
                name: entire piece
                file: Puspa Mekar.tsv
                loop: false
            kawitan:
                name: kawitan
                file: Puspa Mekar kawitan.tsv
                loop: true
            pengecet1:
                name: pengecet 1
                file: Puspa mekar pengecet1.tsv
                loop: true
    puspamekar-calung:
        title: Puspa Mekar CALUNG
        subfolder: puspa mekar
        parts:
            full:
                name: entire piece
                file: Puspa Mekar CALUNG.tsv
                loop: false
    palawakya:
        title: Palawakya
        subfolder: palawakya
        midi_out_file_pattern: !!str "Palawakya_{part_id}_${{midi.midiversion}}.mid"
        pdf_out_file_pattern: !!str "Palawakya_{part_id}_${{midi.midiversion}}.pdf"
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Palawakya.tsv
                loop: false
    palawakya-penyacah:
        title: Palawakya PENYACAH
        subfolder: palawakya
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Palawakya PENYACAH.tsv
                loop: false
    rejangdewa:
        title: Rejang Dewa
        subfolder: rejang dewa
        parts:
            full:
                name: entire piece
                file: rejang dewa_font5.tsv
                loop: false
            intro:
                name: intro
                file: rejang dewa intro_font5.tsv
                loop: true
            pengawak:
                name: pengawak
                file: rejang dewa pengawak_font5.tsv
                loop: true
            pengawak-reyong:
                name: pengawak reyong
                file: rejang dewa pengawak reyong_font5.tsv
                loop: true
            pengecet:
                name: pengecet
                file: rejang dewa pengecet_font5.tsv
                loop: true
        autocorrect_kempyung : false
    sekargendot:
        title: Sekar Gendot
        subfolder: sekar gendot
        instrumentgroup: SEMAR_PAGULINGAN
        autocorrect_kempyung : false
        parts:
            full:
                name: entire piece
                file: Sekar Gendot font5.tsv
                loop: false
    sekargendot-gk:
        title: Sekar Gendot (gong kebyar)
        subfolder: sekar gendot
        instrumentgroup: GONG_KEBYAR
        autocorrect_kempyung : false
        include_in_production_run: false
        parts:
            full:
                name: entire piece
                file: Sekar Gendot font5_GK.tsv
                loop: false
    sinomladrang-sp:
        title: Sinom Ladrang
        subfolder: sinom ladrang
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            full:
                name: entire piece
                file: Sinom Ladrang_SP_font5.tsv
                loop: false
            pengawak:
                name: pengawak
                file: Sinom Ladrang_SP_font5_pengawak.tsv
                loop: true
            pengecet:
                name: pengecet
                file: Sinom Ladrang_SP_font5_pengecet.tsv
                loop: true
    sinomladrang-gk:
        title: Sinom Ladrang (GK)
        subfolder: sinom ladrang
        instrumentgroup: GONG_KEBYAR
        parts:
            full:
                name: entire piece
                file: Sinom Ladrang_GK_ubit4_font5.tsv
                loop: false
    test-gk:
        production: false
        include_in_run_types: [RUN_SINGLE]
        include_in_production_run: false
        title: Test Gong Kebyar
        subfolder: test
        beat_at_end: false            
        instrumentgroup: GONG_KEBYAR
        parts:
            gendinganak2:
                name: gending anak-anak
                file: Gending Anak-Anak.tsv
                loop: false
            cendrawasih:
                name: Cendrawasih
                file: Cendrawasih_complete_font5.tsv
                loop: false
            reyong_13_12:
                name: reyong 1-3, 2-4
                file: reyong13_24_test.tsv
                loop: false
    test-sp:
        production: false
        include_in_run_types: [RUN_SINGLE]
        include_in_production_run: false
        title: Test Semar Pagulingan
        subfolder: test
        beat_at_end: false            
        instrumentgroup: SEMAR_PAGULINGAN
        parts:
            sinomladrang:
                name: Sinom Ladrang
                file: Sinom Ladrang_SP_font5.tsv
                loop: false
