from notation_classes import Character
from notation_constants import InstrumentGroup, InstrumentType, NoteValue

# special note values: -1 = modifies previous note, 0 = rest, 1 = extends previous.
# key ranges: 0=lower range, 1=mid range, 2=higher range (these denote different frequency ranges per instrument)
# stroke: open=unmuted, short=muted immediately after stroke, muted=muted during stroke
# fmt: off
BALIMUSIC4_FONT = [
    Character(symbol='´', unicode=0x00b4, symbol_description='acute', balifont_symbol_description='dash single macron', meaning=NoteValue.EXTENSION, duration=0.5, rest_after=0, description='extends note by half duration'),
    Character(symbol='¨', unicode=0x00a8, symbol_description='trema', balifont_symbol_description='dash double macron', meaning=NoteValue.EXTENSION, duration=0.25, rest_after=0, description='extends note by quarter duration'),
    Character(symbol='#', unicode=0x0023, symbol_description='sharp', balifont_symbol_description='e overdot slashed', meaning=NoteValue.DENG2, duration=0.125, rest_after=0.875, description='deng2 muted'),
    Character(symbol='&', unicode=0x0026, symbol_description='ampersand', balifont_symbol_description='u overdot slashed', meaning=NoteValue.DUNG2, duration=0.125, rest_after=0.875, description='dung2 muted'),
    Character(symbol='(', unicode=0x0028, symbol_description='left round bracket', balifont_symbol_description='o overdot slashed', meaning=NoteValue.DONG2, duration=0.125, rest_after=0.875, description='dong2 muted'),
    Character(symbol='*', unicode=0x002a, symbol_description='', balifont_symbol_description='i (with dot) slashed', meaning=NoteValue.DING2, duration=0.125, rest_after=0.875, description='ding2 muted'),
    Character(symbol='-', unicode=0x002d, symbol_description='hyphen', balifont_symbol_description='dash', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description='extends note duration'),
    Character(symbol='.', unicode=0x002e, symbol_description='period', balifont_symbol_description='dot', meaning=NoteValue.SILENCE, duration=1, rest_after=0, description='silence (muted note) open'),
    Character(symbol='/', unicode=0x002f, symbol_description='', balifont_symbol_description='slash', meaning=NoteValue.MODIFIER_PREV1, duration=0.25, rest_after=0.75, description='long mutes previous note'),
    Character(symbol='^', unicode=0x0302, symbol_description='circumflex', balifont_symbol_description='none currently', meaning=NoteValue.MODIFIER_PREV2, duration=0.75, rest_after=0.25, description='grace note indicator'),
    Character(symbol='3', unicode=0x0033, symbol_description='digit 3', balifont_symbol_description='e overdot', meaning=NoteValue.DENG2, duration=1, rest_after=0, description='deng2 open'),
    Character(symbol='7', unicode=0x0037, symbol_description='digit 7', balifont_symbol_description='u overdot', meaning=NoteValue.DUNG2, duration=1, rest_after=0, description='dung2 open'),
    Character(symbol='8', unicode=0x0038, symbol_description='digit 8', balifont_symbol_description='i (with dot)', meaning=NoteValue.DING2, duration=1, rest_after=0, description='ding2 open'),
    Character(symbol='9', unicode=0x0039, symbol_description='digit 9', balifont_symbol_description='o overdot', meaning=NoteValue.DONG2, duration=1, rest_after=0, description='dong2 open'),
    Character(symbol='=', unicode=0x003d, symbol_description='equal', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description=' open'),
    Character(symbol='A', unicode=0x0041, symbol_description='uppercase A', balifont_symbol_description='a slashed', meaning=NoteValue.DANG1, duration=0.125, rest_after=0.875, description='dang1 muted'),
    Character(symbol='B', unicode=0x0042, symbol_description='uppercase B', balifont_symbol_description='b slashed', meaning=NoteValue.EXTENSION, duration=0.125, rest_after=0.875, description='jet'),
    Character(symbol='D', unicode=0x0044, symbol_description='uppercase D', balifont_symbol_description='e underdot slashed', meaning=NoteValue.DENG0, duration=0.125, rest_after=0.875, description='deng0 muted'),
    Character(symbol='E', unicode=0x0045, symbol_description='uppercase E', balifont_symbol_description='e slashed', meaning=NoteValue.DENG1, duration=0.125, rest_after=0.875, description='deng1 muted'),
    Character(symbol='g', unicode=0x0067, symbol_description='lowercase g', balifont_symbol_description='G', meaning=NoteValue.GIR, duration=4, rest_after=0, description='gir'),
    Character(symbol='I', unicode=0x0049, symbol_description='uppercase I', balifont_symbol_description='dotless i slashed', meaning=NoteValue.DING1, duration=0.125, rest_after=0.875, description='ding1 muted'),
    Character(symbol='J', unicode=0x004a, symbol_description='uppercase J', balifont_symbol_description='u underdot slashed', meaning=NoteValue.DUNG0, duration=0.125, rest_after=0.875, description='dung0 muted'),
    Character(symbol='K', unicode=0x004b, symbol_description='uppercase K', balifont_symbol_description='dotless i underdot', meaning=NoteValue.DING0, duration=1, rest_after=0, description='ding0 open'),
    Character(symbol='L', unicode=0x004c, symbol_description='uppercase L', balifont_symbol_description='o underdot slashed', meaning=NoteValue.DONG0, duration=0.125, rest_after=0.875, description='dong0 muted'),
    Character(symbol='O', unicode=0x004f, symbol_description='uppercase O', balifont_symbol_description='o slashed', meaning=NoteValue.DONG1, duration=0.125, rest_after=0.875, description='dong1 muted'),
    Character(symbol='P', unicode=0x0050, symbol_description='uppercase P', balifont_symbol_description='P', meaning=NoteValue.PUR, duration=4, rest_after=0, description='pur'),
    Character(symbol='Q', unicode=0x0051, symbol_description='uppercase Q', balifont_symbol_description='a overdot slashed', meaning=NoteValue.DANG2, duration=0.125, rest_after=0.875, description='dang2 muted'),
    Character(symbol='R', unicode=0x0052, symbol_description='uppercase R', balifont_symbol_description=' slashed', meaning=NoteValue.EXTENSION, duration=0.125, rest_after=0.875, description='deung muted'),
    Character(symbol='S', unicode=0x0053, symbol_description='uppercase S', balifont_symbol_description=' slashed', meaning=NoteValue.EXTENSION, duration=0.125, rest_after=0.875, description='daing muted'),
    Character(symbol='T', unicode=0x0054, symbol_description='uppercase T', balifont_symbol_description='T', meaning=NoteValue.TONG, duration=4, rest_after=0, description='tong'),
    Character(symbol='U', unicode=0x0055, symbol_description='uppercase U', balifont_symbol_description='u slashed', meaning=NoteValue.DUNG1, duration=0.125, rest_after=0.875, description='dung1 muted'),
    Character(symbol='W', unicode=0x0057, symbol_description='uppercase W', balifont_symbol_description='W', meaning=NoteValue.GIR, duration=4, rest_after=0, description='gir wadon'),
    Character(symbol='X', unicode=0x0058, symbol_description='uppercase X', balifont_symbol_description=' slashed', meaning=NoteValue.TICK_1_PANGGUL, duration=0.125, rest_after=0.875, description='tick muted'),
    Character(symbol='Y', unicode=0x0059, symbol_description='uppercase Y', balifont_symbol_description='e underdot', meaning=NoteValue.DENG0, duration=1, rest_after=0, description='deng0 open'),
    Character(symbol='Z', unicode=0x005a, symbol_description='uppercase Z', balifont_symbol_description='a underdot slashed', meaning=NoteValue.DANG0, duration=0.125, rest_after=0.875, description='dang0 muted'),
    Character(symbol='_', unicode=0x005f, symbol_description='underscore', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description=' open'),
    Character(symbol='a', unicode=0x0061, symbol_description='lowercase a', balifont_symbol_description='a', meaning=NoteValue.DANG1, duration=1, rest_after=0, description='dang1 open'),
    Character(symbol='b', unicode=0x0062, symbol_description='lowercase b', balifont_symbol_description='b', meaning=NoteValue.BYONG, duration=1, rest_after=0, description='byong'),
    Character(symbol='d', unicode=0x0064, symbol_description='lowercase d', balifont_symbol_description='e underdot', meaning=NoteValue.DENG0, duration=1, rest_after=0, description='deng0 open'),
    Character(symbol='e', unicode=0x0065, symbol_description='lowercase e', balifont_symbol_description='e', meaning=NoteValue.DENG1, duration=1, rest_after=0, description='deng1 open'),
    Character(symbol='i', unicode=0x0069, symbol_description='lowercase i', balifont_symbol_description='dotless i', meaning=NoteValue.DING1, duration=1, rest_after=0, description='ding1 open'),
    Character(symbol='j', unicode=0x006a, symbol_description='lowercase j', balifont_symbol_description='u underdot', meaning=NoteValue.DUNG0, duration=1, rest_after=0, description='dung0 open'),
    Character(symbol='k', unicode=0x006b, symbol_description='lowercase k', balifont_symbol_description='dotless i underdot', meaning=NoteValue.DING0, duration=1, rest_after=0, description='ding0 open'),
    Character(symbol='l', unicode=0x006c, symbol_description='lowercase l', balifont_symbol_description='o underdot', meaning=NoteValue.DONG0, duration=1, rest_after=0, description='dong0 open'),
    Character(symbol='n', unicode=0x006e, symbol_description='lowercase n', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0, rest_after=0, description='norot (always followed by note)'),
    Character(symbol='o', unicode=0x006f, symbol_description='lowercase o', balifont_symbol_description='o', meaning=NoteValue.DONG1, duration=1, rest_after=0, description='dong1 open'),
    Character(symbol='p', unicode=0x0070, symbol_description='lowercase p', balifont_symbol_description='P', meaning=NoteValue.PUR, duration=4, rest_after=0, description='pur'),
    Character(symbol='q', unicode=0x0071, symbol_description='lowercase q', balifont_symbol_description='a overdot', meaning=NoteValue.DANG2, duration=1, rest_after=0, description='dang2 open'),
    Character(symbol='r', unicode=0x0072, symbol_description='lowercase r', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description='deung open'),
    Character(symbol='s', unicode=0x0073, symbol_description='lowercase s', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description='daing open'),
    Character(symbol='t', unicode=0x0074, symbol_description='lowercase t', balifont_symbol_description='T', meaning=NoteValue.TONG, duration=4, rest_after=0, description='tong'),
    Character(symbol='u', unicode=0x0075, symbol_description='lowercase u', balifont_symbol_description='u', meaning=NoteValue.DUNG1, duration=1, rest_after=0, description='dung1 open'),
    Character(symbol='w', unicode=0x0077, symbol_description='lowercase w', balifont_symbol_description='L', meaning=NoteValue.GIR, duration=4, rest_after=0, description='gir lanang'),
    Character(symbol='x', unicode=0x0078, symbol_description='lowercase x', balifont_symbol_description='x', meaning=NoteValue.TICK_1_PANGGUL, duration=1, rest_after=0, description='tick open'),
    Character(symbol='y', unicode=0x0079, symbol_description='lowercase y', balifont_symbol_description='', meaning=NoteValue.BYONG, duration=1, rest_after=0, description='byong (old notation)'),
    Character(symbol='z', unicode=0x007a, symbol_description='lowercase z', balifont_symbol_description='a underdot', meaning=NoteValue.DANG0, duration=1, rest_after=0, description='dang0 open'),
    Character(symbol='©', unicode=0x00a9, symbol_description='copyright', balifont_symbol_description='k', meaning=NoteValue.KEP, duration=1, rest_after=0, description='ke open'),
    Character(symbol='ª', unicode=0x00aa, symbol_description='underlined a superscript', balifont_symbol_description='dot with double macron', meaning=NoteValue.SILENCE, duration=0.25, rest_after=0, description='silence quarter duration'),
    Character(symbol='«', unicode=0x00ab, symbol_description='left double chevron quote', balifont_symbol_description='d', meaning=NoteValue.DUT, duration=1, rest_after=0, description='dut open'),
    Character(symbol='¬', unicode=0x00ac, symbol_description='logical not', balifont_symbol_description='n', meaning=NoteValue.KRUM, duration=1, rest_after=0, description='krum open'),
    Character(symbol='®', unicode=0x00ae, symbol_description='registered trademark', balifont_symbol_description='p', meaning=NoteValue.PAK, duration=1, rest_after=0, description='pak open'),
    Character(symbol='¯', unicode=0x00af, symbol_description='high hyphen', balifont_symbol_description='t', meaning=NoteValue.DUT, duration=1, rest_after=0, description='dut open'),
    Character(symbol='°', unicode=0x00b0, symbol_description='degrees', balifont_symbol_description='u', meaning=NoteValue.PUNG, duration=1, rest_after=0, description='pung open'),
    Character(symbol='±', unicode=0x00b1, symbol_description='plusminus', balifont_symbol_description='k', meaning=NoteValue.KEP, duration=1, rest_after=0, description='ke open'),
    Character(symbol='²', unicode=0x00b2, symbol_description='squared (two superscript)', balifont_symbol_description='d', meaning=NoteValue.DUT, duration=1, rest_after=0, description='dut open'),
    Character(symbol='³', unicode=0x00b3, symbol_description='cubed (three superscript)', balifont_symbol_description='n', meaning=NoteValue.KRUM, duration=1, rest_after=0, description='krum open'),
    Character(symbol='µ', unicode=0x00b5, symbol_description='mu', balifont_symbol_description='dot with single macron', meaning=NoteValue.SILENCE, duration=0.5, rest_after=0, description='silence half duration'),
    Character(symbol='¶', unicode=0x00b6, symbol_description='at', balifont_symbol_description='p', meaning=NoteValue.PAK, duration=1, rest_after=0, description='pak open'),
    Character(symbol='·', unicode=0x00b7, symbol_description='dot', balifont_symbol_description='t', meaning=NoteValue.DUT, duration=1, rest_after=0, description='dut open'),
    Character(symbol='¸', unicode=0x00b8, symbol_description='comma', balifont_symbol_description='u', meaning=NoteValue.PUNG, duration=1, rest_after=0, description='pung open'),
    Character(symbol='À', unicode=0x00c0, symbol_description='uppercase A grave', balifont_symbol_description='a underdot slashed, single macron', meaning=NoteValue.DANG0, duration=0.1, rest_after=0.4, description='dang0 half duration long muted'),
    Character(symbol='Á', unicode=0x00c1, symbol_description='uppercase A acute', balifont_symbol_description='a underdot slashed, single macron', meaning=NoteValue.DANG0, duration=0.1, rest_after=0.4, description='dang0 half duration long muted'),
    Character(symbol='Â', unicode=0x00c2, symbol_description='uppercase A circumflex', balifont_symbol_description='a underdot slashed, double macron', meaning=NoteValue.DANG0, duration=0.05, rest_after=0.2, description='dang0 quarter duration muted '),
    Character(symbol='Ä', unicode=0x00c4, symbol_description='uppercase A trema', balifont_symbol_description='a slashed, double macron', meaning=NoteValue.DANG1, duration=0.05, rest_after=0.2, description='dang1 quarter duration muted '),
    Character(symbol='È', unicode=0x00c8, symbol_description='uppercase E grave', balifont_symbol_description='e underdot slashed, single macron', meaning=NoteValue.DENG0, duration=0.1, rest_after=0.4, description='deng0 half duration long muted'),
    Character(symbol='É', unicode=0x00c9, symbol_description='uppercase E acute', balifont_symbol_description='e slashed, single macron', meaning=NoteValue.DENG1, duration=0.1, rest_after=0.4, description='deng1 half duration long muted'),
    Character(symbol='Ê', unicode=0x00ca, symbol_description='uppercase E circumflex', balifont_symbol_description='e underdot slashed, double macron', meaning=NoteValue.DENG0, duration=0.05, rest_after=0.2, description='deng0 quarter duration muted '),
    Character(symbol='Ë', unicode=0x00cb, symbol_description='uppercase E trema', balifont_symbol_description='e slashed, double macron', meaning=NoteValue.DENG1, duration=0.05, rest_after=0.2, description='deng1 quarter duration muted '),
    Character(symbol='Ì', unicode=0x00cc, symbol_description='uppercase I grave', balifont_symbol_description='dotless i underdot slashed, single macron', meaning=NoteValue.DING0, duration=0.1, rest_after=0.4, description='ding0 half duration long muted'),
    Character(symbol='Í', unicode=0x00cd, symbol_description='uppercase I acute', balifont_symbol_description='dotless i slashed, single macron', meaning=NoteValue.DING1, duration=0.1, rest_after=0.4, description='ding1 half duration long muted'),
    Character(symbol='Î', unicode=0x00ce, symbol_description='uppercase I circumflex', balifont_symbol_description='dotless i underdot slashed, double macron', meaning=NoteValue.DING0, duration=0.05, rest_after=0.2, description='ding0 quarter duration muted '),
    Character(symbol='Ï', unicode=0x00cf, symbol_description='uppercase I trema', balifont_symbol_description='dotless i slashed, double macron', meaning=NoteValue.DING1, duration=0.05, rest_after=0.2, description='ding1 quarter duration muted '),
    Character(symbol='Ò', unicode=0x00d2, symbol_description='uppercase O grave', balifont_symbol_description='o underdot slashed, single macron', meaning=NoteValue.DONG0, duration=0.1, rest_after=0.4, description='dong0 half duration long muted'),
    Character(symbol='Ó', unicode=0x00d3, symbol_description='uppercase O acute', balifont_symbol_description='o slashed, single macron', meaning=NoteValue.DONG1, duration=0.1, rest_after=0.4, description='dong1 half duration long muted'),
    Character(symbol='Ô', unicode=0x00d4, symbol_description='uppercase O circumflex', balifont_symbol_description='o underdot slashed, double macron', meaning=NoteValue.DONG0, duration=0.05, rest_after=0.2, description='dong0 quarter duration muted '),
    Character(symbol='Ö', unicode=0x00d6, symbol_description='uppercase O trema', balifont_symbol_description='o slashed, double macron', meaning=NoteValue.DONG1, duration=0.05, rest_after=0.2, description='dong1 quarter duration muted '),
    Character(symbol='Ù', unicode=0x00d9, symbol_description='uppercase U grave', balifont_symbol_description='u underdot slashed, single macron', meaning=NoteValue.DUNG0, duration=0.1, rest_after=0.4, description='dung0 half duration long muted'),
    Character(symbol='Ú', unicode=0x00da, symbol_description='uppercase U acute', balifont_symbol_description='u slashed, single macron', meaning=NoteValue.DUNG1, duration=0.1, rest_after=0.4, description='dung1 half duration long muted'),
    Character(symbol='Û', unicode=0x00db, symbol_description='uppercase U circumflex', balifont_symbol_description='u underdot slashed, double macron', meaning=NoteValue.DUNG0, duration=0.05, rest_after=0.2, description='dung0 quarter duration muted '),
    Character(symbol='Ü', unicode=0x00dc, symbol_description='uppercase U trema', balifont_symbol_description='u slashed, double macron', meaning=NoteValue.DUNG1, duration=0.05, rest_after=0.2, description='dung1 quarter duration muted '),
    Character(symbol='Ý', unicode=0x00dd, symbol_description='uppercase Y acute', balifont_symbol_description='x slashed, single macron', meaning=NoteValue.TICK_1_PANGGUL, duration=0.1, rest_after=0.4, description='tick half duration long muted') ,
    Character(symbol='à', unicode=0x00e0, symbol_description='lowercase a grave', balifont_symbol_description='a underdot single macron', meaning=NoteValue.DANG0, duration=0.5, rest_after=0, description='dang0 half duration'),
    Character(symbol='á', unicode=0x00e1, symbol_description='lowercase a acute', balifont_symbol_description='a single macron', meaning=NoteValue.DANG1, duration=0.5, rest_after=0, description='dang1 half duration'),
    Character(symbol='â', unicode=0x00e2, symbol_description='lowercase a circumflex', balifont_symbol_description='a double macron', meaning=NoteValue.DANG1, duration=0.25, rest_after=0, description='dang1 quarter duration'),
    Character(symbol='ä', unicode=0x00e4, symbol_description='lowercase a trema', balifont_symbol_description='a double macron', meaning=NoteValue.DANG1, duration=0.25, rest_after=0, description='dang1 quarter duration'),
    Character(symbol='è', unicode=0x00e8, symbol_description='lowercase e grave', balifont_symbol_description='e underdot single macron', meaning=NoteValue.DENG0, duration=0.5, rest_after=0, description='deng0 half duration'),
    Character(symbol='é', unicode=0x00e9, symbol_description='lowercase e', balifont_symbol_description='e single macron', meaning=NoteValue.DENG1, duration=0.5, rest_after=0, description='deng1 half duration'),
    Character(symbol='ê', unicode=0x00ea, symbol_description='lowercase e circumflex', balifont_symbol_description='e underdot double macron', meaning=NoteValue.DENG0, duration=0.25, rest_after=0, description='deng0 quarter duration')   ,
    Character(symbol='ë', unicode=0x00eb, symbol_description='lowercase e trema', balifont_symbol_description='e double macron', meaning=NoteValue.DENG1, duration=0.25, rest_after=0, description='deng1 quarter duration'),
    Character(symbol='ì', unicode=0x00ec, symbol_description='lowercase i grave', balifont_symbol_description='e single macron', meaning=NoteValue.DENG1, duration=0.5, rest_after=0, description='deng1 half duration'),
    Character(symbol='í', unicode=0x00ed, symbol_description='lowercase i', balifont_symbol_description='dotless i single macron', meaning=NoteValue.DING1, duration=0.5, rest_after=0, description='ding1 half duration'),
    Character(symbol='î', unicode=0x00ee, symbol_description='lowercase i circumflex', balifont_symbol_description='dotless i underdot double macron', meaning=NoteValue.DING0, duration=0.25, rest_after=0, description='ding0 quarter duration'),
    Character(symbol='ï', unicode=0x00ef, symbol_description='lowercase i trema', balifont_symbol_description='dotless i double macron', meaning=NoteValue.DING1, duration=0.25, rest_after=0, description='ding1 quarter duration')        ,
    Character(symbol='ò', unicode=0x00f2, symbol_description='lowercase o grave', balifont_symbol_description='o underdot double macron', meaning=NoteValue.DONG0, duration=0.25, rest_after=0, description='dong0 quarter duration')        ,
    Character(symbol='ó', unicode=0x00f3, symbol_description='lowercase o', balifont_symbol_description='o single macron', meaning=NoteValue.DONG1, duration=0.5, rest_after=0, description='dong1 half duration'),
    Character(symbol='ô', unicode=0x00f4, symbol_description='lowercase o circumflex', balifont_symbol_description='o underdot double macron', meaning=NoteValue.DONG0, duration=0.25, rest_after=0, description='dong0 quarter duration')   ,
    Character(symbol='ö', unicode=0x00f6, symbol_description='lowercase o trema', balifont_symbol_description='o double macron', meaning=NoteValue.DONG1, duration=0.25, rest_after=0, description='dong1 quarter duration'),
    Character(symbol='ù', unicode=0x00f9, symbol_description='lowercase u grave', balifont_symbol_description='u underdot single macron', meaning=NoteValue.DUNG0, duration=0.5, rest_after=0, description='dung0 half duration'),
    Character(symbol='ú', unicode=0x00fa, symbol_description='lowercase u acute', balifont_symbol_description='u single macron', meaning=NoteValue.DUNG1, duration=0.5, rest_after=0, description='dung1 half duration'),
    Character(symbol='û', unicode=0x00fb, symbol_description='lowercase u circumflex', balifont_symbol_description='u underdot double macron', meaning=NoteValue.DUNG0, duration=0.25, rest_after=0, description='dung0 quarter duration')   ,
    Character(symbol='ü', unicode=0x00fc, symbol_description='lowercase u trema', balifont_symbol_description='u double macron', meaning=NoteValue.DUNG1, duration=0.25, rest_after=0, description='dung1 quarter duration'),
    Character(symbol='ý', unicode=0x00fd, symbol_description='lowercase y acute', balifont_symbol_description='x single macron', meaning=NoteValue.TICK_1_PANGGUL, duration=0.5, rest_after=0, description='tick half duration'),
    Character(symbol='ÿ', unicode=0x00ff, symbol_description='lowercase y trema', balifont_symbol_description='x double macron', meaning=NoteValue.TICK_1_PANGGUL, duration=0.25, rest_after=0, description='tick quarter duration'),
    Character(symbol='Ā', unicode=0x0100, symbol_description='uppercase A macron', balifont_symbol_description='a overdot slashed, single macron', meaning=NoteValue.DANG2, duration=0.1, rest_after=0.4, description='dang2 half duration long muted'),
    Character(symbol='ā', unicode=0x0101, symbol_description='lowercase a macron', balifont_symbol_description='a overdot single macron', meaning=NoteValue.DANG2, duration=0.5, rest_after=0, description='dang2 half duration'),
    Character(symbol='Ă', unicode=0x0102, symbol_description='uppercase A breve', balifont_symbol_description='a overdot slashed, double macron', meaning=NoteValue.DANG2, duration=0.05, rest_after=0.2, description='dang2 quarter duration muted '),
    Character(symbol='ă', unicode=0x0103, symbol_description='lowercase a breve', balifont_symbol_description='a overdot double macron', meaning=NoteValue.DANG2, duration=0.25, rest_after=0, description='dang2 quarter duration')       ,
    Character(symbol='Ē', unicode=0x0112, symbol_description='uppercase E macron', balifont_symbol_description='e overdot slashed, single macron', meaning=NoteValue.DENG2, duration=0.1, rest_after=0.4, description='deng2 half duration long muted'),
    Character(symbol='ē', unicode=0x0113, symbol_description='lowercase e macron', balifont_symbol_description='e overdot single macron', meaning=NoteValue.DENG2, duration=0.5, rest_after=0, description='deng2 half duration'),
    Character(symbol='Ĕ', unicode=0x0114, symbol_description='uppercase E breve', balifont_symbol_description='e overdot slashed, double macron', meaning=NoteValue.DENG2, duration=0.05, rest_after=0.2, description='deng2 quarter duration muted '),
    Character(symbol='ĕ', unicode=0x0115, symbol_description='lowercase e breve', balifont_symbol_description='e overdot double macron', meaning=NoteValue.DENG2, duration=0.25, rest_after=0, description='deng2 quarter duration')       ,
    Character(symbol='Ī', unicode=0x012a, symbol_description='uppercase i macron', balifont_symbol_description='i (with dot) slashed, single macron', meaning=NoteValue.DING2, duration=0.1, rest_after=0.4, description='ding2 half duration long muted'),
    Character(symbol='ī', unicode=0x012b, symbol_description='lowercase i macron', balifont_symbol_description='i (with dot) single macron', meaning=NoteValue.DING2, duration=0.5, rest_after=0, description='ding2 half duration')       ,
    Character(symbol='Ĭ', unicode=0x012c, symbol_description='uppercase I breve', balifont_symbol_description='i (with dot) slashed, double macron', meaning=NoteValue.DING2, duration=0.05, rest_after=0.2, description='ding2 quarter duration muted '),
    Character(symbol='ĭ', unicode=0x012d, symbol_description='lowercase i breve', balifont_symbol_description='i (with dot) double macron', meaning=NoteValue.DING2, duration=0.25, rest_after=0, description='ding2 quarter duration')    ,
    Character(symbol='Ō', unicode=0x014c, symbol_description='uppercase O macron', balifont_symbol_description='o overdot slashed, single macron', meaning=NoteValue.DONG2, duration=0.1, rest_after=0.4, description='dong2 half duration long muted'),
    Character(symbol='ō', unicode=0x014d, symbol_description='lowercase o macron', balifont_symbol_description='o overdot single macron', meaning=NoteValue.DONG2, duration=0.5, rest_after=0, description='dong2 half duration'),
    Character(symbol='Ŏ', unicode=0x014e, symbol_description='uppercase O breve', balifont_symbol_description='o overdot slashed, double macron', meaning=NoteValue.DONG2, duration=0.05, rest_after=0.2, description='dong2 quarter duration muted '),
    Character(symbol='ŏ', unicode=0x014f, symbol_description='lowercase o breve', balifont_symbol_description='o overdot double macron', meaning=NoteValue.DONG2, duration=0.25, rest_after=0, description='dong2 quarter duration')       ,
    Character(symbol='Ŕ', unicode=0x0154, symbol_description='uppercase R acute', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.1, rest_after=0.4, description='deung half duration muted'),
    Character(symbol='ŕ', unicode=0x0155, symbol_description='lowercase r acute', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.5, rest_after=0, description='deung open half duration'),
    Character(symbol='Ŗ', unicode=0x0156, symbol_description='uppercase R undercomma', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.05, rest_after=0.2, description='deung quarter duration muted')    ,
    Character(symbol='ŗ', unicode=0x0157, symbol_description='lowercase r undercomma', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.25, rest_after=0, description='deung open quarter duration')       ,
    Character(symbol='Ś', unicode=0x015a, symbol_description='uppercase S acute', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.1, rest_after=0.4, description='daing half duration muted'),
    Character(symbol='ś', unicode=0x015b, symbol_description='lowercase s acute', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.5, rest_after=0, description='daing open half duration'),
    Character(symbol='Ş', unicode=0x015e, symbol_description='uppercase S cedille', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.05, rest_after=0.2, description='daing quarter duration muted')       ,
    Character(symbol='ş', unicode=0x015f, symbol_description='lowercase s cedille', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=0.25, rest_after=0, description='daing open quarter duration'),
    Character(symbol='Ū', unicode=0x016a, symbol_description='uppercase U macron', balifont_symbol_description='u overdot slashed, single macron', meaning=NoteValue.DUNG2, duration=0.1, rest_after=0.4, description='dung2 half duration long muted'),
    Character(symbol='ū', unicode=0x016b, symbol_description='lowercase u macron', balifont_symbol_description='u overdot single macron', meaning=NoteValue.DUNG2, duration=0.5, rest_after=0, description='dung2 half duration'),
    Character(symbol='Ŭ', unicode=0x016c, symbol_description='uppercase U breve', balifont_symbol_description='u overdot slashed, double macron', meaning=NoteValue.DUNG2, duration=0.05, rest_after=0.2, description='dung2 quarter duration muted '),
    Character(symbol='ŭ', unicode=0x016d, symbol_description='lowercase u breve', balifont_symbol_description='u overdot double macron', meaning=NoteValue.DUNG2, duration=0.25, rest_after=0, description='dung2 quarter duration')       ,
    Character(symbol='Ÿ', unicode=0x0178, symbol_description='uppercase Y trema', balifont_symbol_description='x slashed, double macron', meaning=NoteValue.TICK_1_PANGGUL, duration=0.05, rest_after=0.2, description='tick quarter duration muted '),
    Character(symbol='Ž', unicode=0x017d, symbol_description='uppercase Z caron', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description='long mutes previous note, half duration')   ,
    Character(symbol='ž', unicode=0x017e, symbol_description='lowercase Z caron', balifont_symbol_description='', meaning=NoteValue.EXTENSION, duration=1, rest_after=0, description='long mutes previous note, quarter duration'),
]

if __name__ == "__main__":
    MIDI_NOTES_DICT = {(note.instrumentgroup, note.instrumentname, note.notevalue): note.midi for note in MIDI_NOTES}
    BALIMUSIC4_FONT_DICT = {character.symbol: character for character in BALIMUSIC4_FONT}
    symbol = "-"
    character = BALIMUSIC4_FONT_DICT[symbol]
    if character.meaning.isnote:
        value = MIDI_NOTES_DICT[(InstrumentGroup.GONG_KEBYAR, InstrumentType.PEMADE, character.meaning)]
    else:
        value = character.meaning
    print(value)
